---
# Extra Packages for Enterprise Linux (EPEL)
- name: Extra Packages for Enterprise Linux (EPEL)
  yum: name=epel-release state=latest

# Libraries and utilities for RedHat
- name: Libraries and utilities
  yum: name={{ item }} state=present
  with_items: "{{ yum_libraries_utilities }}"

# IPTABLES
- name: Start IPTABLES service
  service: name=iptables enabled=yes state=started

# SELinux
- name: SELinux should be enforcing
  selinux:
    policy: targeted
    state: enforcing

  # Date and time
- name: Remove old timezone file
  file: path=/etc/localtime state=absent
  run_once: true
- name: Set Asia/Kolkata timezone
  file: src=/usr/share/zoneinfo/Asia/Kolkata dest=/etc/localtime state=link
  run_once: true
- name: Ensure NTP is running
  service: name=ntpd state=started enabled=yes
  run_once: true