---
# Extra Packages for Enterprise Linux (EPEL)
- name: Extra Packages for Enterprise Linux (EPEL)
  yum: name=epel-release state=latest

# Libraries and utilities for RedHat
- name: Libraries and utilities
  yum: name={{ item }} state=present
  with_items: "{{ yum_libraries_utilities }}"

# IPTABLES
- name: Start IPTABLES service
  service: name=iptables enabled=yes state=started

# SELinux
- name: SELinux should be enforcing
  selinux:
    policy: targeted
    state: enforcing
    reboot_required: false

# TimeZone
- name: Set TimeZone
  timezone: Asia/Kolkata